services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - ./backend/.env
    command: ["node", "server.js"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
